// <auto-generated />
using System;
using HebergementManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HebergementManager.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("HebergementManager.Api.Models.CategorieEquipement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategorieEquipement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Confort & intérieur"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Cuisine & repas"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Services & commodités"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Extérieur & loisirs"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Famille & sécurité"
                        });
                });

            modelBuilder.Entity("HebergementManager.Api.Models.Equipements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieEquipementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieEquipementId");

                    b.ToTable("Equipements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieEquipementId = 1,
                            Nom = "WiFi gratuit"
                        },
                        new
                        {
                            Id = 2,
                            CategorieEquipementId = 1,
                            Nom = "Climatisation"
                        },
                        new
                        {
                            Id = 3,
                            CategorieEquipementId = 1,
                            Nom = "Télévision"
                        },
                        new
                        {
                            Id = 4,
                            CategorieEquipementId = 1,
                            Nom = "Chauffage"
                        },
                        new
                        {
                            Id = 5,
                            CategorieEquipementId = 1,
                            Nom = "Machine à laver"
                        },
                        new
                        {
                            Id = 6,
                            CategorieEquipementId = 1,
                            Nom = "Sèche-cheveux"
                        },
                        new
                        {
                            Id = 7,
                            CategorieEquipementId = 1,
                            Nom = "Fer à repasser"
                        },
                        new
                        {
                            Id = 8,
                            CategorieEquipementId = 2,
                            Nom = "Cuisine équipée"
                        },
                        new
                        {
                            Id = 9,
                            CategorieEquipementId = 2,
                            Nom = "Réfrigérateur"
                        },
                        new
                        {
                            Id = 10,
                            CategorieEquipementId = 2,
                            Nom = "Micro-ondes"
                        },
                        new
                        {
                            Id = 11,
                            CategorieEquipementId = 2,
                            Nom = "Lave-vaisselle"
                        },
                        new
                        {
                            Id = 12,
                            CategorieEquipementId = 2,
                            Nom = "Cafetière"
                        },
                        new
                        {
                            Id = 13,
                            CategorieEquipementId = 2,
                            Nom = "Ustensiles de cuisine"
                        },
                        new
                        {
                            Id = 14,
                            CategorieEquipementId = 3,
                            Nom = "Parking gratuit"
                        },
                        new
                        {
                            Id = 15,
                            CategorieEquipementId = 3,
                            Nom = "Ascenseur"
                        },
                        new
                        {
                            Id = 16,
                            CategorieEquipementId = 3,
                            Nom = "Service de ménage"
                        },
                        new
                        {
                            Id = 17,
                            CategorieEquipementId = 4,
                            Nom = "Balcon / Terrasse"
                        },
                        new
                        {
                            Id = 18,
                            CategorieEquipementId = 4,
                            Nom = "Jardin"
                        },
                        new
                        {
                            Id = 19,
                            CategorieEquipementId = 4,
                            Nom = "Piscine"
                        },
                        new
                        {
                            Id = 20,
                            CategorieEquipementId = 4,
                            Nom = "Salle de sport"
                        },
                        new
                        {
                            Id = 21,
                            CategorieEquipementId = 4,
                            Nom = "Barbecue"
                        },
                        new
                        {
                            Id = 22,
                            CategorieEquipementId = 5,
                            Nom = "Lit bébé"
                        },
                        new
                        {
                            Id = 23,
                            CategorieEquipementId = 5,
                            Nom = "Chaise haute"
                        },
                        new
                        {
                            Id = 24,
                            CategorieEquipementId = 5,
                            Nom = "Détecteur de fumée"
                        },
                        new
                        {
                            Id = 25,
                            CategorieEquipementId = 5,
                            Nom = "Détecteur de monoxyde de carbone"
                        },
                        new
                        {
                            Id = 26,
                            CategorieEquipementId = 5,
                            Nom = "Trousse de premiers secours"
                        });
                });

            modelBuilder.Entity("HebergementManager.Api.Models.Hebergement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixParNuit")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeHebergementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypeHebergementId");

                    b.ToTable("Hebergements");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.HebergementEquipement", b =>
                {
                    b.Property<int>("HebergementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HebergementId", "EquipementId");

                    b.HasIndex("EquipementId");

                    b.ToTable("HebergementEquipements");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateArrivee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDepart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HebergementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombrePersonnes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelephoneClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HebergementId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.TypeHebergement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TypeHebergements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Appartement"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Chambre"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Maison"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Villa"
                        });
                });

            modelBuilder.Entity("HebergementManager.Api.Models.Equipements", b =>
                {
                    b.HasOne("HebergementManager.Api.Models.CategorieEquipement", "Categorie")
                        .WithMany("Equipement")
                        .HasForeignKey("CategorieEquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.Hebergement", b =>
                {
                    b.HasOne("HebergementManager.Api.Models.TypeHebergement", "Type")
                        .WithMany("Hebergement")
                        .HasForeignKey("TypeHebergementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.HebergementEquipement", b =>
                {
                    b.HasOne("HebergementManager.Api.Models.Equipements", "Equipement")
                        .WithMany("HebergementEquipements")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HebergementManager.Api.Models.Hebergement", "Hebergement")
                        .WithMany("HebergementEquipements")
                        .HasForeignKey("HebergementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");

                    b.Navigation("Hebergement");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.Reservation", b =>
                {
                    b.HasOne("HebergementManager.Api.Models.Hebergement", "Hebergement")
                        .WithMany("Reservations")
                        .HasForeignKey("HebergementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hebergement");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.CategorieEquipement", b =>
                {
                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.Equipements", b =>
                {
                    b.Navigation("HebergementEquipements");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.Hebergement", b =>
                {
                    b.Navigation("HebergementEquipements");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HebergementManager.Api.Models.TypeHebergement", b =>
                {
                    b.Navigation("Hebergement");
                });
#pragma warning restore 612, 618
        }
    }
}
